### ISSUE TITLE
[FEATURE] Add pinging on Discord webhook

### ISSUE THREAD

**Issue by Menacho15** [ItsLeon15/Bug-Reports#19]
Add an option to ping a role/user when a bug report is sent using the Discord webhook feature.

**Comment by ItsLeon15** [comment]
Thanks for the suggestion, it is currently being implemented and should be in the next release!

**Comment by ItsLeon15** [comment]
@Menacho15 This has now been added in the latest release **v0.12.3**

**Comment by Menacho15** [comment]
Thank you for being that fast. I'll update it on my server.
